<?php

/**
 * @file
 * Contains style_library_entity.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function style_library_entity_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the style_library_entity module.
    case 'help.page.style_library_entity':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a Style Library Entity type for storing css and js resources for themes and modules to use') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function style_library_entity_theme() {
  $theme = [];
  $theme['style_library_entity'] = [
    'render element' => 'elements',
    'file' => 'style_library_entity.page.inc',
    'template' => 'style_library_entity',
  ];
  $theme['style_library_entity_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'style_library_entity.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function style_library_entity_theme_suggestions_style_library_entity(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#style_library_entity'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'style_library_entity__' . $sanitized_view_mode;
  $suggestions[] = 'style_library_entity__' . $entity->bundle();
  $suggestions[] = 'style_library_entity__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'style_library_entity__' . $entity->id();
  $suggestions[] = 'style_library_entity__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
